#Tue, 04 Aug 2026 12:08:19 +0000
#
# SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
#
# Copyright (c) 2012-2026 mgm technology partners GmbH
#
# Dual License
# ------------
# This source file is part of the mgm A12 Platform and available under
# a choice of two different licenses:
#
# 1. Open-Source License - EUPL v1.2
#    You may redistribute and/or modify this file under the terms of the
#    European Union Public License, version 1.2 - see https://eupl.eu/.
#
# 2. Commercial License
#    Alternatively, you may obtain a commercial license from
#    mgm technology partners GmbH, that permits use of this software
#    under different terms (including support and maintenance services).
#
#    Please contact a12-license@mgm-tp.com for more information.
#
# You must select and comply with exactly one of the above license options.
#
# Warranty Disclaimer (applies to either option)
# ----------------------------------------------
# THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND,
# WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
# LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
#

# Project configuration
group=com.mgmtp.a12.projecttemplate
#The exact Assistants version is maintained in package.json in [releaseline].[ext-release].[patch] semver format.
a12ReleaseLine=2026.06
# TODO: Update to your project JIRA code
projectJiraCode=A12BD|A12PT

# Deployment
# TODO-Start: Replace these values with your docker-registry
dockerRegistryForPublish=docker.io
dockerRegistryForRead=docker.io
# TODO-End: Replace these values with your docker-registry

# CONFIG: Set 'false' if you do not use credentials
dockerUseCredentials=false
# CONFIG: Base image for Spring Boot Layer Index approach for building docker image.
dockerSeverBaseImage=eclipse-temurin\:25-jre-jammy
dockerClientBaseImage=nginx\:1.29.3-alpine-slim

# Service names for calculating Docker image tags
clientName=frontend
serverName=server
serverInitName=server-init

# Docker
#dockerHost=tcp://some-remote-host:2375

# Gradle configuration
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.console=plain

# CONFIG: Set 'true' if you want to enable the configuration cache for Gradle builds
# see https://docs.gradle.org/9.3.1/userguide/configuration_cache.html
org.gradle.configuration-cache=false

# Code quality
checkstyleVersion=10.15.0
skipLintFormat=false
skipCheckstyle=false
