#!/usr/bin/env node
/**
 * Renders compose/keycloak/*.template into the files Keycloak actually reads, substituting
 * ${VAR} from the repository's .env.
 *
 * This exists because Keycloak does not substitute anything itself. Its realm import stores
 * `${env.MY_VAR}` as that literal string -- verified against 26.5.3, and a long-standing gap
 * (keycloak/keycloak#20199). So the choice is between committing the passwords next to the realm
 * or rendering them in, and D-023 chose rendering: every secret in the stack lives in .env and
 * nowhere else.
 *
 * Node rather than `envsubst`, which is not installed on macOS by default; node already is, since
 * the Runtime and the client both need it.
 *
 * Substitution is strict on purpose. A missing variable would otherwise reach Keycloak as a
 * literal `${HUMAN_PASSWORD}` -- an import that succeeds and a password nobody can guess, which is
 * a far worse failure than not starting at all.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..", "..");
const ENV_FILE = join(REPO_ROOT, ".env");

const TEMPLATES = ["A12Realm-realm.json.template", "A12Realm-users-0.json.template", "keycloak.env.template"];

/**
 * A deliberately small .env reader: `KEY=value`, optionally single- or double-quoted, `#`
 * comments and blank lines skipped. It is not a shell, and does not pretend to be one -- no
 * interpolation, no `export`, no line continuations. The file it reads is generated by
 * `just setup` from .env.example, so its shape is known.
 */
function readEnvFile(path) {
    const env = {};
    for (const raw of readFileSync(path, "utf8").split("\n")) {
        const line = raw.trim();
        if (line === "" || line.startsWith("#")) continue;
        const eq = line.indexOf("=");
        if (eq === -1) continue;
        const key = line.slice(0, eq).trim();
        let value = line.slice(eq + 1).trim();
        if (
            (value.startsWith("'") && value.endsWith("'")) ||
            (value.startsWith('"') && value.endsWith('"'))
        ) {
            value = value.slice(1, -1);
        }
        env[key] = value;
    }
    return env;
}

if (!existsSync(ENV_FILE)) {
    console.error(`No ${ENV_FILE}. Run \`just setup\` first — it writes one from .env.example.`);
    process.exit(1);
}

const env = readEnvFile(ENV_FILE);
const missing = new Set();
const placeholders = new Set();

// Render everything first, write nothing until it all substituted cleanly. A half-rendered set
// would leave Keycloak importing one good file and one full of empty passwords.
const outputs = new Map();
for (const template of TEMPLATES) {
    const source = readFileSync(join(HERE, template), "utf8");
    const rendered = source.replace(/\$\{([A-Z0-9_]+)\}/g, (_match, name) => {
        const value = env[name];
        if (value === undefined || value === "") {
            missing.add(name);
            return "";
        }
        // A value still saying CHANGE_ME means `just setup` was skipped or edited out. Catch it
        // here rather than let it become somebody's password.
        if (value.includes("CHANGE_ME")) placeholders.add(name);
        return value;
    });
    outputs.set(template.replace(/\.template$/, ""), rendered);
}

if (missing.size > 0) {
    console.error(`.env is missing: ${[...missing].sort().join(", ")}`);
    process.exit(1);
}
if (placeholders.size > 0) {
    console.error(`.env still has CHANGE_ME placeholders: ${[...placeholders].sort().join(", ")}`);
    process.exit(1);
}

for (const [name, contents] of outputs) writeFileSync(join(HERE, name), contents);

console.log(`rendered ${TEMPLATES.length} Keycloak files from .env`);
