/*
 * SPDX-License-Identifier: EUPL-1.2
 *
 * Copyright (c) 2026 Till Gartner
 *
 * Part of Assistants.
 *
 * Licensed under the European Union Public Licence, version 1.2 - see
 * https://eupl.eu/ and the LICENSE file at the root of this repository.
 * Distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.
 */

/**
 * Driving the stack from a test, which only the ADR-0004 restart test needs.
 *
 * Restarting is the whole point of that test: if waiting were a running process, killing the
 * process would lose the wait. It is not, so it does not.
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

import { BASE_URL, COMPOSE_ARGS, REPO_ROOT, THINGSTORE_URL } from "./config";
import { sleep } from "./thingstore";

/** `docker compose … restart <services>` — the same invocation `just restart` uses. */
/**
 * Restart services, always taking the frontend with them.
 *
 * nginx resolves its upstreams once, at startup. Restarting `server` gives it a new container IP,
 * and the frontend then proxies `/api/**` to an address nobody is listening on — every call comes
 * back 502 and the login form never renders. The frontend has to come along.
 */
export function restartServices(services: string[]): void {
    const withFrontend = services.includes("frontend") ? services : [...services, "frontend"];
    execFileSync("docker", [...COMPOSE_ARGS, "restart", ...withFrontend], {
        cwd: REPO_ROOT,
        encoding: "utf-8",
        stdio: "pipe",
        timeout: 180_000
    });
}

async function responds(url: string): Promise<boolean> {
    try {
        const response = await fetch(url, { signal: AbortSignal.timeout(5_000) });
        return response.ok;
    } catch {
        return false;
    }
}

/** Wait until the ThingStore and the UserInterface answer again — what `just wait` does. */
export async function waitForStack(timeoutMs = 240_000): Promise<void> {
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
        if ((await responds(`${THINGSTORE_URL}/actuator/health`)) && (await responds(BASE_URL))) {
            return;
        }
        await sleep(2_000);
    }
    throw new Error(`The stack did not come back within ${timeoutMs} ms — try \`just logs\`.`);
}

/**
 * Where the generated compose override goes. Gitignored, and cleaned by `just clean`.
 */
const OVERRIDE = path.join(REPO_ROOT, "e2e", "test-results", "runtime-override.yml");

/** `docker compose`, with an extra override file wedged in behind the base one. */
function compose(overridePath: string | undefined, ...rest: string[]): void {
    const files = overridePath ? ["-f", overridePath] : [];
    // The base file first, then the override: later `-f` wins, which is the whole mechanism.
    const args = [...COMPOSE_ARGS.slice(0, 3), ...files, ...COMPOSE_ARGS.slice(3), ...rest];
    execFileSync("docker", args, { cwd: REPO_ROOT, encoding: "utf-8", stdio: "pipe", timeout: 300_000 });
}

/**
 * Recreate the Runtime container with extra environment, and optionally an extra read-only mount.
 *
 * **Why not `restart`.** `restart` reuses the container, and a container's environment is fixed when
 * it is created — so a restart would run the old `MAIL_HOST=''` again and the test would wait for a
 * poll that never happens. `up -d` recreates it, which is the only way new environment gets in.
 *
 * **Why not editing `.env`.** That file is the developer's, it holds every secret in the stack
 * (D-023), and a suite that rewrites it leaves the machine changed when a run is killed halfway. A
 * generated override file is a separate artefact in `test-results/`; deleting it is the whole of the
 * undo, and {@link restoreRuntime} is that undo.
 *
 * `--no-deps` because `server`, `keycloak` and `firefly-bootstrap` are already up and are not what
 * is being reconfigured; without it compose considers all of them and can take the stack with it.
 */
export function recreateRuntimeWith(environment: Record<string, string>, mounts: Record<string, string> = {}): void {
    const lines = [
        "# Generated by e2e/utils/stack.ts. Not committed, not hand-edited — see recreateRuntimeWith().",
        "services:",
        "    runtime:",
        "        environment:"
    ];
    for (const [name, value] of Object.entries(environment)) {
        lines.push(`            ${name}: ${JSON.stringify(value)}`);
    }
    if (Object.keys(mounts).length > 0) {
        lines.push("        volumes:");
        for (const [host, target] of Object.entries(mounts)) {
            // Absolute, because which directory a relative path in an override file is resolved
            // against has changed between compose versions and is not worth depending on.
            lines.push(`            - ${JSON.stringify(`${path.resolve(host)}:${target}:ro`)}`);
        }
    }

    mkdirSync(path.dirname(OVERRIDE), { recursive: true });
    writeFileSync(OVERRIDE, `${lines.join("\n")}\n`, "utf-8");
    compose(OVERRIDE, "up", "-d", "--no-deps", "runtime");
}

/** Put the Runtime back the way `.env` and `compose/docker-compose.yml` describe it. */
export function restoreRuntime(): void {
    rmSync(OVERRIDE, { force: true });
    // `--force-recreate`, because dropping the override changes the configuration back to what the
    // *previous* container was created from as far as compose's own hash is concerned in some
    // versions, and a no-op here would leave the test's environment in place for the whole suite.
    compose(undefined, "up", "-d", "--no-deps", "--force-recreate", "runtime");
}

/**
 * Wait until the Runtime's log says the thing only a correctly configured Runtime can say.
 *
 * Not the container's health check: that reports "did the last scan finish", with a 90-second start
 * period and a 15-second interval, so it answers long after the Runtime is working and it cannot
 * distinguish a Runtime that read the new environment from one that did not. The startup line names
 * the host and the allowed-sender count, so waiting for it is waiting for the configuration.
 */
export async function waitForRuntimeLog(contains: string, timeoutMs = 180_000): Promise<string> {
    const deadline = Date.now() + timeoutMs;
    for (;;) {
        // `docker logs` against a container that is mid-recreation answers with an error rather
        // than an empty log, and that is a "not yet", not a failure.
        let logs = "";
        try {
            logs = execFileSync("docker", ["logs", "--tail", "400", "assistants_runtime"], {
                encoding: "utf-8",
                stdio: ["ignore", "pipe", "pipe"]
            });
        } catch {
            logs = "";
        }
        const line = logs.split("\n").find((candidate) => candidate.includes(contains));
        if (line) {
            return line;
        }
        if (Date.now() > deadline) {
            throw new Error(`The Runtime never logged ${JSON.stringify(contains)} within ${timeoutMs} ms.`);
        }
        await sleep(1_000);
    }
}
