-- Switch the seven built-in bookkeeping Operations to dynamic (ADR-0025).
--
-- Each Operation's Source, egress and language are written onto its Operation Thing, and the two
-- flags the registry and the inbound gate now read OFF the Thing for a dynamic Operation — Mutating
-- and ClientReadable — are set here too, because the values these Things carried from their built-in
-- days were never authoritative and cannot be trusted. ClientReadable is set true only on
-- listAccounts and listTransactions (the two the Dashboard reads); Mutating true only on
-- postTransaction and createAccount.
--
-- Idempotent: the WHERE clause matches only Things not yet switched (Implementation is not already
-- 'dynamic'), so a second run is a no-op. Atomic: one UPDATE, so a failure at row 5 of 7 rolls the
-- whole statement back — there is no half-migrated state to clean up; re-run it.
--
-- ORDER — run it OFFLINE, in the same maintenance window as the image swap, never against a live old
-- Runtime. Either interleaving observed by a running Runtime strands the seven Operations: a migrated
-- Thing (Implementation: dynamic) meeting the still-compiled code drops as 'ambiguous', and the new
-- image meeting an un-migrated Thing drops as 'unimplemented'. With the Runtime down for the swap,
-- neither window is ever live.
--
--     docker exec -i <PROJECT>_postgres psql -U <DATASERVICES_USERNAME> -d <DATASERVICES_DB> \
--         < import/migrations/2026-08-19-bookkeeping-operations-dynamic.sql
--
-- RE-INDEX — this writes the document rows directly, which the A12 server does not observe until it
-- re-indexes at startup. Restart (or recreate) the SERVER after applying the migration so its query
-- index picks up the new Implementation/Source/Egress — otherwise the Operations overview and form
-- show the pre-migration (blank) values, even though the runtime reads the migrated rows fresh.
-- Verified 2026-08-20: the server re-indexed the migrated dynamic documents with no restart loop.
--
-- REVERSIBILITY — rollback is NOT code-only. Restoring the previous image (compiled bookkeeping.*
-- back) while the Things still read Implementation: dynamic drops all seven as 'ambiguous'. To roll
-- back, restore the old image AND revert the Thing fields in the same offline window — the
-- down-migration below does that (Implementation to built-in, Source cleared). It is commented out;
-- uncomment and run it, then bring the old image up.
--
-- GENERATED by scripts/generate-bookkeeping-migration.mjs from import/operations/bookkeeping/ — the
-- embedded Source matches the seed byte for byte, so bootstrap reports no divergence. Regenerate it
-- rather than editing it by hand.

UPDATE document AS d
SET content = (
    d.content::jsonb
    || jsonb_build_object(
        'Operation',
        (d.content::jsonb -> 'Operation')
        || jsonb_build_object(
            'Implementation', 'dynamic',
            'Language', 'typescript',
            'Egress', 'bookkeeping',
        'Mutating', (
            CASE d.content::jsonb #>> '{Operation,Key}'
            WHEN 'bookkeeping.getBalance' THEN false
            WHEN 'bookkeeping.listAccounts' THEN false
            WHEN 'bookkeeping.listOpenItems' THEN false
            WHEN 'bookkeeping.listTransactions' THEN false
            WHEN 'bookkeeping.getBudgetReport' THEN false
            WHEN 'bookkeeping.createAccount' THEN true
            WHEN 'bookkeeping.postTransaction' THEN true
            ELSE false
            END
        ),
        'ClientReadable', (
            CASE d.content::jsonb #>> '{Operation,Key}'
            WHEN 'bookkeeping.getBalance' THEN false
            WHEN 'bookkeeping.listAccounts' THEN true
            WHEN 'bookkeeping.listOpenItems' THEN false
            WHEN 'bookkeeping.listTransactions' THEN true
            WHEN 'bookkeeping.getBudgetReport' THEN false
            WHEN 'bookkeeping.createAccount' THEN false
            WHEN 'bookkeeping.postTransaction' THEN false
            ELSE false
            END
        ),
        'Source', (
            CASE d.content::jsonb #>> '{Operation,Key}'
            WHEN 'bookkeeping.getBalance' THEN $src0$// Bookkeeping egress — shared prelude (ADR-0025).
//
// This block is prepended to every bookkeeping Operation's Source before it is stored, so each
// Operation reads as its own `execute` plus these helpers. It is the part of FireflyConnector that
// was worth keeping: the HTTP call wrapper, account name -> id resolution, the chart-of-accounts
// cache (now `host.cache`, TTL'd and invalidated by createAccount), category resolution, the 422
// field-name table, and the transaction projection. Everything it reaches is on `host`; there are
// no imports, because the Operation Host hands the Source its one capability rather than loading one.

// Firefly's own internal accounts are not part of any chart of accounts a household books to. This
// is a deny-list on purpose: an allow-list once missed that Firefly answers `liabilities` where it
// accepts `liability`, and hid the payables account (BUG-02).
const INTERNAL_ACCOUNT_TYPES = ["initial-balance", "reconciliation", "import"];
function isBookable(type) {
    return INTERNAL_ACCOUNT_TYPES.indexOf(String(type).toLowerCase()) === -1;
}

function todayIso() {
    return new Date().toISOString().slice(0, 10);
}

// One call to Firefly, through the injected client. The credential is attached by the Host and never
// seen here. A non-2xx throws with Firefly's own message where it gave one — the reader sees exactly
// the HTTP this makes. Callers that need the raw status (postTransaction) use host.http.request.
async function fireflyCall(host, method, path, options) {
    const opts = options || {};
    const response = await host.http.request({ method: method, path: path, query: opts.query, body: opts.body });
    if (!response.ok) {
        const said = response.body && response.body.message ? response.body.message : "Firefly HTTP " + response.status;
        host.error(said);
    }
    return response.body;
}

// The chart of accounts, cached per egress. `refresh` bypasses the cache the way the old connector's
// `listAccounts(true)` did; createAccount evicts the key so a freshly made account is resolvable at once.
async function loadAccounts(host, refresh) {
    if (!refresh) {
        const cached = host.cache.get("accounts");
        if (cached) return cached;
    }
    const body = await fireflyCall(host, "GET", "/api/v1/accounts", { query: { limit: 200 } });
    const rows = (body && body.data) || [];
    const accounts = rows
        .map(function (row) {
            const a = row.attributes || {};
            return {
                id: row.id,
                name: String(a.name || ""),
                type: String(a.type || ""),
                currentBalance: a.current_balance,
                currencyCode: a.currency_code,
            };
        })
        .filter(function (a) {
            return isBookable(a.type);
        });
    host.cache.set("accounts", accounts);
    return accounts;
}

function accountAmbiguous(host, name, candidates) {
    const listed = candidates
        .map(function (a) {
            return '"' + a.name + '" [' + a.type + "]";
        })
        .join(" and ");
    host.error(
        'The account name "' +
            name +
            '" is ambiguous — it matches ' +
            listed +
            ". Use the exact name as it appears in the chart of accounts.",
    );
}

// Resolve a name to an id, or fail loudly. An exact match wins outright; else a single caseless
// match; two of either is ambiguous. Cache first, then one refresh-and-retry, then a 404 naming
// every account that does exist. Never let Firefly invent an account, never guess between two.
async function resolveAccountId(host, name) {
    function pick(accounts) {
        const exact = accounts.filter(function (a) {
            return a.name === name;
        });
        if (exact.length === 1) return exact[0];
        if (exact.length > 1) accountAmbiguous(host, name, exact);
        const caseless = accounts.filter(function (a) {
            return a.name.toLowerCase() === String(name).trim().toLowerCase();
        });
        if (caseless.length === 1) return caseless[0];
        if (caseless.length > 1) accountAmbiguous(host, name, caseless);
        return undefined;
    }
    const found = pick(await loadAccounts(host, false));
    if (found) return found.id;
    const refreshed = await loadAccounts(host, true);
    const retry = pick(refreshed);
    if (retry) return retry.id;
    host.error(
        'No account named "' +
            name +
            '". Existing accounts: ' +
            refreshed
                .map(function (a) {
                    return a.name;
                })
                .join(", "),
    );
}

async function currencyOf(host, name) {
    const accounts = await loadAccounts(host, false);
    const match = accounts.filter(function (a) {
        return a.name.toLowerCase() === String(name).trim().toLowerCase();
    })[0];
    return match ? match.currencyCode : undefined;
}

async function loadCategories(host, refresh) {
    if (!refresh) {
        const cached = host.cache.get("categories");
        if (cached) return cached;
    }
    const body = await fireflyCall(host, "GET", "/api/v1/categories", { query: { limit: 200 } });
    const rows = (body && body.data) || [];
    const categories = rows.map(function (row) {
        return { id: row.id, name: String((row.attributes || {}).name || "") };
    });
    host.cache.set("categories", categories);
    return categories;
}

// Category is resolved to an id, never posted by name, so a typo cannot silently create a category.
async function resolveCategoryId(host, name) {
    function pick(categories) {
        return categories.filter(function (c) {
            return c.name.toLowerCase() === String(name).trim().toLowerCase();
        })[0];
    }
    const found = pick(await loadCategories(host, false));
    if (found) return found.id;
    const refreshed = await loadCategories(host, true);
    const retry = pick(refreshed);
    if (retry) return retry.id;
    host.error(
        'No category named "' +
            name +
            '". Existing categories: ' +
            (refreshed.length
                ? refreshed
                      .map(function (c) {
                          return c.name;
                      })
                      .join(", ")
                : "(none yet)") +
            ". Leave the category out, or ask the User to create it.",
    );
}

// Firefly names a field `source_id`; the model gave a `sourceAccount`. This maps a rejection back
// into the model's own vocabulary so a 422 reads as advice, not as Firefly's internals.
const FIREFLY_FIELD_NAMES = {
    source_id: "sourceAccount",
    source_name: "sourceAccount",
    destination_id: "destinationAccount",
    destination_name: "destinationAccount",
    budget_name: "budgetName",
    category_id: "categoryName",
    category_name: "categoryName",
    currency_code: "currencyCode",
    amount: "amount",
    date: "date",
    description: "description",
    type: "type",
    notes: "notes",
};

function describeRejection(details, splits) {
    const errors = details && details.errors;
    if (!errors || Object.keys(errors).length === 0) return undefined;
    const lines = [];
    const seen = {};
    for (const key of Object.keys(errors)) {
        const messages = errors[key];
        const match = /^transactions\.(\d+)\.(.+)$/.exec(key);
        const index = match ? Number(match[1]) : 0;
        const field = match ? match[2] : key;
        const property = FIREFLY_FIELD_NAMES[field];
        const supplied = property && splits[index] ? splits[index][property] : undefined;
        const label = property || field;
        const where = splits.length > 1 ? " (posting " + (index + 1) + ")" : "";
        const said = messages
            .join(" ")
            .replace(/ID "\d+"/g, supplied !== undefined ? '"' + String(supplied) + '"' : "that account")
            .replace(/ or name ""\.?/g, "");
        const line = label + where + (supplied === undefined ? "" : ' "' + String(supplied) + '"') + ": " + said.trim();
        if (!seen[line]) {
            seen[line] = true;
            lines.push(line);
        }
    }
    return (
        "Firefly refused this posting.\n" +
        lines
            .map(function (l) {
                return "- " + l;
            })
            .join("\n")
    );
}

// One Firefly transaction group -> one row per split, in the model's own field names.
function projectTransactionGroup(group) {
    const attributes = group.attributes || {};
    const splits = attributes.transactions || [];
    return splits.map(function (split) {
        return {
            transactionId: group.id,
            date: String(split.date || "").slice(0, 10),
            description: split.description,
            amount: split.amount,
            currency: split.currency_code,
            from: split.source_name,
            to: split.destination_name,
            category: split.category_name || undefined,
            budget: split.budget_name || undefined,
            bookedUnderKey: split.external_id || undefined,
            tags: split.tags || undefined,
        };
    });
}

// bookkeeping.getBalance — the current balance of one account.
async function execute(args, host) {
    const accountName = String(args.account || "");
    const id = await resolveAccountId(host, accountName);
    const body = await fireflyCall(host, "GET", "/api/v1/accounts/" + id);
    const a = (body && body.data && body.data.attributes) || {};
    return {
        account: accountName,
        balance: String(a.current_balance || "0"),
        currency: String(a.currency_code || "EUR"),
    };
}
$src0$
            WHEN 'bookkeeping.listAccounts' THEN $src1$// Bookkeeping egress — shared prelude (ADR-0025).
//
// This block is prepended to every bookkeeping Operation's Source before it is stored, so each
// Operation reads as its own `execute` plus these helpers. It is the part of FireflyConnector that
// was worth keeping: the HTTP call wrapper, account name -> id resolution, the chart-of-accounts
// cache (now `host.cache`, TTL'd and invalidated by createAccount), category resolution, the 422
// field-name table, and the transaction projection. Everything it reaches is on `host`; there are
// no imports, because the Operation Host hands the Source its one capability rather than loading one.

// Firefly's own internal accounts are not part of any chart of accounts a household books to. This
// is a deny-list on purpose: an allow-list once missed that Firefly answers `liabilities` where it
// accepts `liability`, and hid the payables account (BUG-02).
const INTERNAL_ACCOUNT_TYPES = ["initial-balance", "reconciliation", "import"];
function isBookable(type) {
    return INTERNAL_ACCOUNT_TYPES.indexOf(String(type).toLowerCase()) === -1;
}

function todayIso() {
    return new Date().toISOString().slice(0, 10);
}

// One call to Firefly, through the injected client. The credential is attached by the Host and never
// seen here. A non-2xx throws with Firefly's own message where it gave one — the reader sees exactly
// the HTTP this makes. Callers that need the raw status (postTransaction) use host.http.request.
async function fireflyCall(host, method, path, options) {
    const opts = options || {};
    const response = await host.http.request({ method: method, path: path, query: opts.query, body: opts.body });
    if (!response.ok) {
        const said = response.body && response.body.message ? response.body.message : "Firefly HTTP " + response.status;
        host.error(said);
    }
    return response.body;
}

// The chart of accounts, cached per egress. `refresh` bypasses the cache the way the old connector's
// `listAccounts(true)` did; createAccount evicts the key so a freshly made account is resolvable at once.
async function loadAccounts(host, refresh) {
    if (!refresh) {
        const cached = host.cache.get("accounts");
        if (cached) return cached;
    }
    const body = await fireflyCall(host, "GET", "/api/v1/accounts", { query: { limit: 200 } });
    const rows = (body && body.data) || [];
    const accounts = rows
        .map(function (row) {
            const a = row.attributes || {};
            return {
                id: row.id,
                name: String(a.name || ""),
                type: String(a.type || ""),
                currentBalance: a.current_balance,
                currencyCode: a.currency_code,
            };
        })
        .filter(function (a) {
            return isBookable(a.type);
        });
    host.cache.set("accounts", accounts);
    return accounts;
}

function accountAmbiguous(host, name, candidates) {
    const listed = candidates
        .map(function (a) {
            return '"' + a.name + '" [' + a.type + "]";
        })
        .join(" and ");
    host.error(
        'The account name "' +
            name +
            '" is ambiguous — it matches ' +
            listed +
            ". Use the exact name as it appears in the chart of accounts.",
    );
}

// Resolve a name to an id, or fail loudly. An exact match wins outright; else a single caseless
// match; two of either is ambiguous. Cache first, then one refresh-and-retry, then a 404 naming
// every account that does exist. Never let Firefly invent an account, never guess between two.
async function resolveAccountId(host, name) {
    function pick(accounts) {
        const exact = accounts.filter(function (a) {
            return a.name === name;
        });
        if (exact.length === 1) return exact[0];
        if (exact.length > 1) accountAmbiguous(host, name, exact);
        const caseless = accounts.filter(function (a) {
            return a.name.toLowerCase() === String(name).trim().toLowerCase();
        });
        if (caseless.length === 1) return caseless[0];
        if (caseless.length > 1) accountAmbiguous(host, name, caseless);
        return undefined;
    }
    const found = pick(await loadAccounts(host, false));
    if (found) return found.id;
    const refreshed = await loadAccounts(host, true);
    const retry = pick(refreshed);
    if (retry) return retry.id;
    host.error(
        'No account named "' +
            name +
            '". Existing accounts: ' +
            refreshed
                .map(function (a) {
                    return a.name;
                })
                .join(", "),
    );
}

async function currencyOf(host, name) {
    const accounts = await loadAccounts(host, false);
    const match = accounts.filter(function (a) {
        return a.name.toLowerCase() === String(name).trim().toLowerCase();
    })[0];
    return match ? match.currencyCode : undefined;
}

async function loadCategories(host, refresh) {
    if (!refresh) {
        const cached = host.cache.get("categories");
        if (cached) return cached;
    }
    const body = await fireflyCall(host, "GET", "/api/v1/categories", { query: { limit: 200 } });
    const rows = (body && body.data) || [];
    const categories = rows.map(function (row) {
        return { id: row.id, name: String((row.attributes || {}).name || "") };
    });
    host.cache.set("categories", categories);
    return categories;
}

// Category is resolved to an id, never posted by name, so a typo cannot silently create a category.
async function resolveCategoryId(host, name) {
    function pick(categories) {
        return categories.filter(function (c) {
            return c.name.toLowerCase() === String(name).trim().toLowerCase();
        })[0];
    }
    const found = pick(await loadCategories(host, false));
    if (found) return found.id;
    const refreshed = await loadCategories(host, true);
    const retry = pick(refreshed);
    if (retry) return retry.id;
    host.error(
        'No category named "' +
            name +
            '". Existing categories: ' +
            (refreshed.length
                ? refreshed
                      .map(function (c) {
                          return c.name;
                      })
                      .join(", ")
                : "(none yet)") +
            ". Leave the category out, or ask the User to create it.",
    );
}

// Firefly names a field `source_id`; the model gave a `sourceAccount`. This maps a rejection back
// into the model's own vocabulary so a 422 reads as advice, not as Firefly's internals.
const FIREFLY_FIELD_NAMES = {
    source_id: "sourceAccount",
    source_name: "sourceAccount",
    destination_id: "destinationAccount",
    destination_name: "destinationAccount",
    budget_name: "budgetName",
    category_id: "categoryName",
    category_name: "categoryName",
    currency_code: "currencyCode",
    amount: "amount",
    date: "date",
    description: "description",
    type: "type",
    notes: "notes",
};

function describeRejection(details, splits) {
    const errors = details && details.errors;
    if (!errors || Object.keys(errors).length === 0) return undefined;
    const lines = [];
    const seen = {};
    for (const key of Object.keys(errors)) {
        const messages = errors[key];
        const match = /^transactions\.(\d+)\.(.+)$/.exec(key);
        const index = match ? Number(match[1]) : 0;
        const field = match ? match[2] : key;
        const property = FIREFLY_FIELD_NAMES[field];
        const supplied = property && splits[index] ? splits[index][property] : undefined;
        const label = property || field;
        const where = splits.length > 1 ? " (posting " + (index + 1) + ")" : "";
        const said = messages
            .join(" ")
            .replace(/ID "\d+"/g, supplied !== undefined ? '"' + String(supplied) + '"' : "that account")
            .replace(/ or name ""\.?/g, "");
        const line = label + where + (supplied === undefined ? "" : ' "' + String(supplied) + '"') + ": " + said.trim();
        if (!seen[line]) {
            seen[line] = true;
            lines.push(line);
        }
    }
    return (
        "Firefly refused this posting.\n" +
        lines
            .map(function (l) {
                return "- " + l;
            })
            .join("\n")
    );
}

// One Firefly transaction group -> one row per split, in the model's own field names.
function projectTransactionGroup(group) {
    const attributes = group.attributes || {};
    const splits = attributes.transactions || [];
    return splits.map(function (split) {
        return {
            transactionId: group.id,
            date: String(split.date || "").slice(0, 10),
            description: split.description,
            amount: split.amount,
            currency: split.currency_code,
            from: split.source_name,
            to: split.destination_name,
            category: split.category_name || undefined,
            budget: split.budget_name || undefined,
            bookedUnderKey: split.external_id || undefined,
            tags: split.tags || undefined,
        };
    });
}

// bookkeeping.listAccounts — the chart of accounts, optionally filtered by Firefly type.
async function execute(args, host) {
    const accounts = await loadAccounts(host, true); // always fresh, as the connector did
    const wanted = String(args.type || "").trim().toLowerCase();
    function matches(accountType) {
        const t = String(accountType).toLowerCase();
        // BUG-02: Firefly's read API answers `liabilities` where its write API accepts `liability`.
        // Matching on the shared `liabilit` prefix is what makes the payables account visible here.
        return wanted === "" || t === wanted || (t.indexOf("liabilit") === 0 && wanted.indexOf("liabilit") === 0);
    }
    return accounts
        .filter(function (a) {
            return matches(a.type);
        })
        .map(function (a) {
            return { name: a.name, type: a.type, balance: a.currentBalance, currency: a.currencyCode };
        });
}
$src1$
            WHEN 'bookkeeping.listOpenItems' THEN $src2$// Bookkeeping egress — shared prelude (ADR-0025).
//
// This block is prepended to every bookkeeping Operation's Source before it is stored, so each
// Operation reads as its own `execute` plus these helpers. It is the part of FireflyConnector that
// was worth keeping: the HTTP call wrapper, account name -> id resolution, the chart-of-accounts
// cache (now `host.cache`, TTL'd and invalidated by createAccount), category resolution, the 422
// field-name table, and the transaction projection. Everything it reaches is on `host`; there are
// no imports, because the Operation Host hands the Source its one capability rather than loading one.

// Firefly's own internal accounts are not part of any chart of accounts a household books to. This
// is a deny-list on purpose: an allow-list once missed that Firefly answers `liabilities` where it
// accepts `liability`, and hid the payables account (BUG-02).
const INTERNAL_ACCOUNT_TYPES = ["initial-balance", "reconciliation", "import"];
function isBookable(type) {
    return INTERNAL_ACCOUNT_TYPES.indexOf(String(type).toLowerCase()) === -1;
}

function todayIso() {
    return new Date().toISOString().slice(0, 10);
}

// One call to Firefly, through the injected client. The credential is attached by the Host and never
// seen here. A non-2xx throws with Firefly's own message where it gave one — the reader sees exactly
// the HTTP this makes. Callers that need the raw status (postTransaction) use host.http.request.
async function fireflyCall(host, method, path, options) {
    const opts = options || {};
    const response = await host.http.request({ method: method, path: path, query: opts.query, body: opts.body });
    if (!response.ok) {
        const said = response.body && response.body.message ? response.body.message : "Firefly HTTP " + response.status;
        host.error(said);
    }
    return response.body;
}

// The chart of accounts, cached per egress. `refresh` bypasses the cache the way the old connector's
// `listAccounts(true)` did; createAccount evicts the key so a freshly made account is resolvable at once.
async function loadAccounts(host, refresh) {
    if (!refresh) {
        const cached = host.cache.get("accounts");
        if (cached) return cached;
    }
    const body = await fireflyCall(host, "GET", "/api/v1/accounts", { query: { limit: 200 } });
    const rows = (body && body.data) || [];
    const accounts = rows
        .map(function (row) {
            const a = row.attributes || {};
            return {
                id: row.id,
                name: String(a.name || ""),
                type: String(a.type || ""),
                currentBalance: a.current_balance,
                currencyCode: a.currency_code,
            };
        })
        .filter(function (a) {
            return isBookable(a.type);
        });
    host.cache.set("accounts", accounts);
    return accounts;
}

function accountAmbiguous(host, name, candidates) {
    const listed = candidates
        .map(function (a) {
            return '"' + a.name + '" [' + a.type + "]";
        })
        .join(" and ");
    host.error(
        'The account name "' +
            name +
            '" is ambiguous — it matches ' +
            listed +
            ". Use the exact name as it appears in the chart of accounts.",
    );
}

// Resolve a name to an id, or fail loudly. An exact match wins outright; else a single caseless
// match; two of either is ambiguous. Cache first, then one refresh-and-retry, then a 404 naming
// every account that does exist. Never let Firefly invent an account, never guess between two.
async function resolveAccountId(host, name) {
    function pick(accounts) {
        const exact = accounts.filter(function (a) {
            return a.name === name;
        });
        if (exact.length === 1) return exact[0];
        if (exact.length > 1) accountAmbiguous(host, name, exact);
        const caseless = accounts.filter(function (a) {
            return a.name.toLowerCase() === String(name).trim().toLowerCase();
        });
        if (caseless.length === 1) return caseless[0];
        if (caseless.length > 1) accountAmbiguous(host, name, caseless);
        return undefined;
    }
    const found = pick(await loadAccounts(host, false));
    if (found) return found.id;
    const refreshed = await loadAccounts(host, true);
    const retry = pick(refreshed);
    if (retry) return retry.id;
    host.error(
        'No account named "' +
            name +
            '". Existing accounts: ' +
            refreshed
                .map(function (a) {
                    return a.name;
                })
                .join(", "),
    );
}

async function currencyOf(host, name) {
    const accounts = await loadAccounts(host, false);
    const match = accounts.filter(function (a) {
        return a.name.toLowerCase() === String(name).trim().toLowerCase();
    })[0];
    return match ? match.currencyCode : undefined;
}

async function loadCategories(host, refresh) {
    if (!refresh) {
        const cached = host.cache.get("categories");
        if (cached) return cached;
    }
    const body = await fireflyCall(host, "GET", "/api/v1/categories", { query: { limit: 200 } });
    const rows = (body && body.data) || [];
    const categories = rows.map(function (row) {
        return { id: row.id, name: String((row.attributes || {}).name || "") };
    });
    host.cache.set("categories", categories);
    return categories;
}

// Category is resolved to an id, never posted by name, so a typo cannot silently create a category.
async function resolveCategoryId(host, name) {
    function pick(categories) {
        return categories.filter(function (c) {
            return c.name.toLowerCase() === String(name).trim().toLowerCase();
        })[0];
    }
    const found = pick(await loadCategories(host, false));
    if (found) return found.id;
    const refreshed = await loadCategories(host, true);
    const retry = pick(refreshed);
    if (retry) return retry.id;
    host.error(
        'No category named "' +
            name +
            '". Existing categories: ' +
            (refreshed.length
                ? refreshed
                      .map(function (c) {
                          return c.name;
                      })
                      .join(", ")
                : "(none yet)") +
            ". Leave the category out, or ask the User to create it.",
    );
}

// Firefly names a field `source_id`; the model gave a `sourceAccount`. This maps a rejection back
// into the model's own vocabulary so a 422 reads as advice, not as Firefly's internals.
const FIREFLY_FIELD_NAMES = {
    source_id: "sourceAccount",
    source_name: "sourceAccount",
    destination_id: "destinationAccount",
    destination_name: "destinationAccount",
    budget_name: "budgetName",
    category_id: "categoryName",
    category_name: "categoryName",
    currency_code: "currencyCode",
    amount: "amount",
    date: "date",
    description: "description",
    type: "type",
    notes: "notes",
};

function describeRejection(details, splits) {
    const errors = details && details.errors;
    if (!errors || Object.keys(errors).length === 0) return undefined;
    const lines = [];
    const seen = {};
    for (const key of Object.keys(errors)) {
        const messages = errors[key];
        const match = /^transactions\.(\d+)\.(.+)$/.exec(key);
        const index = match ? Number(match[1]) : 0;
        const field = match ? match[2] : key;
        const property = FIREFLY_FIELD_NAMES[field];
        const supplied = property && splits[index] ? splits[index][property] : undefined;
        const label = property || field;
        const where = splits.length > 1 ? " (posting " + (index + 1) + ")" : "";
        const said = messages
            .join(" ")
            .replace(/ID "\d+"/g, supplied !== undefined ? '"' + String(supplied) + '"' : "that account")
            .replace(/ or name ""\.?/g, "");
        const line = label + where + (supplied === undefined ? "" : ' "' + String(supplied) + '"') + ": " + said.trim();
        if (!seen[line]) {
            seen[line] = true;
            lines.push(line);
        }
    }
    return (
        "Firefly refused this posting.\n" +
        lines
            .map(function (l) {
                return "- " + l;
            })
            .join("\n")
    );
}

// One Firefly transaction group -> one row per split, in the model's own field names.
function projectTransactionGroup(group) {
    const attributes = group.attributes || {};
    const splits = attributes.transactions || [];
    return splits.map(function (split) {
        return {
            transactionId: group.id,
            date: String(split.date || "").slice(0, 10),
            description: split.description,
            amount: split.amount,
            currency: split.currency_code,
            from: split.source_name,
            to: split.destination_name,
            category: split.category_name || undefined,
            budget: split.budget_name || undefined,
            bookedUnderKey: split.external_id || undefined,
            tags: split.tags || undefined,
        };
    });
}

// bookkeeping.listOpenItems — unpaid invoices and unclaimed reimbursements: the non-zero balances
// on payable and receivable accounts.
async function execute(args, host) {
    const accounts = await loadAccounts(host, true);
    return accounts.filter(function (a) {
        const type = String(a.type).toLowerCase();
        // `liabilit` prefix again (BUG-02): a payables account reads as `liabilities` here.
        const isOpenItemAccount =
            /payable|receivable/i.test(a.name) && (type.indexOf("liabilit") === 0 || type === "asset" || type === "debt");
        const balance = Number(a.currentBalance || "0");
        return isOpenItemAccount && Number.isFinite(balance) && Math.abs(balance) > 0.0001;
    });
}
$src2$
            WHEN 'bookkeeping.listTransactions' THEN $src3$// Bookkeeping egress — shared prelude (ADR-0025).
//
// This block is prepended to every bookkeeping Operation's Source before it is stored, so each
// Operation reads as its own `execute` plus these helpers. It is the part of FireflyConnector that
// was worth keeping: the HTTP call wrapper, account name -> id resolution, the chart-of-accounts
// cache (now `host.cache`, TTL'd and invalidated by createAccount), category resolution, the 422
// field-name table, and the transaction projection. Everything it reaches is on `host`; there are
// no imports, because the Operation Host hands the Source its one capability rather than loading one.

// Firefly's own internal accounts are not part of any chart of accounts a household books to. This
// is a deny-list on purpose: an allow-list once missed that Firefly answers `liabilities` where it
// accepts `liability`, and hid the payables account (BUG-02).
const INTERNAL_ACCOUNT_TYPES = ["initial-balance", "reconciliation", "import"];
function isBookable(type) {
    return INTERNAL_ACCOUNT_TYPES.indexOf(String(type).toLowerCase()) === -1;
}

function todayIso() {
    return new Date().toISOString().slice(0, 10);
}

// One call to Firefly, through the injected client. The credential is attached by the Host and never
// seen here. A non-2xx throws with Firefly's own message where it gave one — the reader sees exactly
// the HTTP this makes. Callers that need the raw status (postTransaction) use host.http.request.
async function fireflyCall(host, method, path, options) {
    const opts = options || {};
    const response = await host.http.request({ method: method, path: path, query: opts.query, body: opts.body });
    if (!response.ok) {
        const said = response.body && response.body.message ? response.body.message : "Firefly HTTP " + response.status;
        host.error(said);
    }
    return response.body;
}

// The chart of accounts, cached per egress. `refresh` bypasses the cache the way the old connector's
// `listAccounts(true)` did; createAccount evicts the key so a freshly made account is resolvable at once.
async function loadAccounts(host, refresh) {
    if (!refresh) {
        const cached = host.cache.get("accounts");
        if (cached) return cached;
    }
    const body = await fireflyCall(host, "GET", "/api/v1/accounts", { query: { limit: 200 } });
    const rows = (body && body.data) || [];
    const accounts = rows
        .map(function (row) {
            const a = row.attributes || {};
            return {
                id: row.id,
                name: String(a.name || ""),
                type: String(a.type || ""),
                currentBalance: a.current_balance,
                currencyCode: a.currency_code,
            };
        })
        .filter(function (a) {
            return isBookable(a.type);
        });
    host.cache.set("accounts", accounts);
    return accounts;
}

function accountAmbiguous(host, name, candidates) {
    const listed = candidates
        .map(function (a) {
            return '"' + a.name + '" [' + a.type + "]";
        })
        .join(" and ");
    host.error(
        'The account name "' +
            name +
            '" is ambiguous — it matches ' +
            listed +
            ". Use the exact name as it appears in the chart of accounts.",
    );
}

// Resolve a name to an id, or fail loudly. An exact match wins outright; else a single caseless
// match; two of either is ambiguous. Cache first, then one refresh-and-retry, then a 404 naming
// every account that does exist. Never let Firefly invent an account, never guess between two.
async function resolveAccountId(host, name) {
    function pick(accounts) {
        const exact = accounts.filter(function (a) {
            return a.name === name;
        });
        if (exact.length === 1) return exact[0];
        if (exact.length > 1) accountAmbiguous(host, name, exact);
        const caseless = accounts.filter(function (a) {
            return a.name.toLowerCase() === String(name).trim().toLowerCase();
        });
        if (caseless.length === 1) return caseless[0];
        if (caseless.length > 1) accountAmbiguous(host, name, caseless);
        return undefined;
    }
    const found = pick(await loadAccounts(host, false));
    if (found) return found.id;
    const refreshed = await loadAccounts(host, true);
    const retry = pick(refreshed);
    if (retry) return retry.id;
    host.error(
        'No account named "' +
            name +
            '". Existing accounts: ' +
            refreshed
                .map(function (a) {
                    return a.name;
                })
                .join(", "),
    );
}

async function currencyOf(host, name) {
    const accounts = await loadAccounts(host, false);
    const match = accounts.filter(function (a) {
        return a.name.toLowerCase() === String(name).trim().toLowerCase();
    })[0];
    return match ? match.currencyCode : undefined;
}

async function loadCategories(host, refresh) {
    if (!refresh) {
        const cached = host.cache.get("categories");
        if (cached) return cached;
    }
    const body = await fireflyCall(host, "GET", "/api/v1/categories", { query: { limit: 200 } });
    const rows = (body && body.data) || [];
    const categories = rows.map(function (row) {
        return { id: row.id, name: String((row.attributes || {}).name || "") };
    });
    host.cache.set("categories", categories);
    return categories;
}

// Category is resolved to an id, never posted by name, so a typo cannot silently create a category.
async function resolveCategoryId(host, name) {
    function pick(categories) {
        return categories.filter(function (c) {
            return c.name.toLowerCase() === String(name).trim().toLowerCase();
        })[0];
    }
    const found = pick(await loadCategories(host, false));
    if (found) return found.id;
    const refreshed = await loadCategories(host, true);
    const retry = pick(refreshed);
    if (retry) return retry.id;
    host.error(
        'No category named "' +
            name +
            '". Existing categories: ' +
            (refreshed.length
                ? refreshed
                      .map(function (c) {
                          return c.name;
                      })
                      .join(", ")
                : "(none yet)") +
            ". Leave the category out, or ask the User to create it.",
    );
}

// Firefly names a field `source_id`; the model gave a `sourceAccount`. This maps a rejection back
// into the model's own vocabulary so a 422 reads as advice, not as Firefly's internals.
const FIREFLY_FIELD_NAMES = {
    source_id: "sourceAccount",
    source_name: "sourceAccount",
    destination_id: "destinationAccount",
    destination_name: "destinationAccount",
    budget_name: "budgetName",
    category_id: "categoryName",
    category_name: "categoryName",
    currency_code: "currencyCode",
    amount: "amount",
    date: "date",
    description: "description",
    type: "type",
    notes: "notes",
};

function describeRejection(details, splits) {
    const errors = details && details.errors;
    if (!errors || Object.keys(errors).length === 0) return undefined;
    const lines = [];
    const seen = {};
    for (const key of Object.keys(errors)) {
        const messages = errors[key];
        const match = /^transactions\.(\d+)\.(.+)$/.exec(key);
        const index = match ? Number(match[1]) : 0;
        const field = match ? match[2] : key;
        const property = FIREFLY_FIELD_NAMES[field];
        const supplied = property && splits[index] ? splits[index][property] : undefined;
        const label = property || field;
        const where = splits.length > 1 ? " (posting " + (index + 1) + ")" : "";
        const said = messages
            .join(" ")
            .replace(/ID "\d+"/g, supplied !== undefined ? '"' + String(supplied) + '"' : "that account")
            .replace(/ or name ""\.?/g, "");
        const line = label + where + (supplied === undefined ? "" : ' "' + String(supplied) + '"') + ": " + said.trim();
        if (!seen[line]) {
            seen[line] = true;
            lines.push(line);
        }
    }
    return (
        "Firefly refused this posting.\n" +
        lines
            .map(function (l) {
                return "- " + l;
            })
            .join("\n")
    );
}

// One Firefly transaction group -> one row per split, in the model's own field names.
function projectTransactionGroup(group) {
    const attributes = group.attributes || {};
    const splits = attributes.transactions || [];
    return splits.map(function (split) {
        return {
            transactionId: group.id,
            date: String(split.date || "").slice(0, 10),
            description: split.description,
            amount: split.amount,
            currency: split.currency_code,
            from: split.source_name,
            to: split.destination_name,
            category: split.category_name || undefined,
            budget: split.budget_name || undefined,
            bookedUnderKey: split.external_id || undefined,
            tags: split.tags || undefined,
        };
    });
}

// bookkeeping.listTransactions — the register, in a date range, optionally for one account.
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;
async function execute(args, host) {
    for (const field of ["start", "end"]) {
        const value = String(args[field] || "");
        if (!ISO_DATE.test(value)) {
            host.error(
                "`" +
                    field +
                    '` must be a calendar date written yyyy-mm-dd, e.g. 2026-01-31 — got "' +
                    value +
                    '". Give the first and last day of the window explicitly.',
            );
        }
    }
    const limit = Math.min(200, Math.max(1, Number(args.limit || 25) || 25)); // default 25, at most 200
    const query = { start: String(args.start), end: String(args.end), limit: limit };
    let path = "/api/v1/transactions";
    if (args.account) {
        const id = await resolveAccountId(host, String(args.account));
        path = "/api/v1/accounts/" + id + "/transactions";
    }
    const body = await fireflyCall(host, "GET", path, { query: query });
    const groups = (body && body.data) || [];
    return groups.flatMap(projectTransactionGroup);
}
$src3$
            WHEN 'bookkeeping.getBudgetReport' THEN $src4$// Bookkeeping egress — shared prelude (ADR-0025).
//
// This block is prepended to every bookkeeping Operation's Source before it is stored, so each
// Operation reads as its own `execute` plus these helpers. It is the part of FireflyConnector that
// was worth keeping: the HTTP call wrapper, account name -> id resolution, the chart-of-accounts
// cache (now `host.cache`, TTL'd and invalidated by createAccount), category resolution, the 422
// field-name table, and the transaction projection. Everything it reaches is on `host`; there are
// no imports, because the Operation Host hands the Source its one capability rather than loading one.

// Firefly's own internal accounts are not part of any chart of accounts a household books to. This
// is a deny-list on purpose: an allow-list once missed that Firefly answers `liabilities` where it
// accepts `liability`, and hid the payables account (BUG-02).
const INTERNAL_ACCOUNT_TYPES = ["initial-balance", "reconciliation", "import"];
function isBookable(type) {
    return INTERNAL_ACCOUNT_TYPES.indexOf(String(type).toLowerCase()) === -1;
}

function todayIso() {
    return new Date().toISOString().slice(0, 10);
}

// One call to Firefly, through the injected client. The credential is attached by the Host and never
// seen here. A non-2xx throws with Firefly's own message where it gave one — the reader sees exactly
// the HTTP this makes. Callers that need the raw status (postTransaction) use host.http.request.
async function fireflyCall(host, method, path, options) {
    const opts = options || {};
    const response = await host.http.request({ method: method, path: path, query: opts.query, body: opts.body });
    if (!response.ok) {
        const said = response.body && response.body.message ? response.body.message : "Firefly HTTP " + response.status;
        host.error(said);
    }
    return response.body;
}

// The chart of accounts, cached per egress. `refresh` bypasses the cache the way the old connector's
// `listAccounts(true)` did; createAccount evicts the key so a freshly made account is resolvable at once.
async function loadAccounts(host, refresh) {
    if (!refresh) {
        const cached = host.cache.get("accounts");
        if (cached) return cached;
    }
    const body = await fireflyCall(host, "GET", "/api/v1/accounts", { query: { limit: 200 } });
    const rows = (body && body.data) || [];
    const accounts = rows
        .map(function (row) {
            const a = row.attributes || {};
            return {
                id: row.id,
                name: String(a.name || ""),
                type: String(a.type || ""),
                currentBalance: a.current_balance,
                currencyCode: a.currency_code,
            };
        })
        .filter(function (a) {
            return isBookable(a.type);
        });
    host.cache.set("accounts", accounts);
    return accounts;
}

function accountAmbiguous(host, name, candidates) {
    const listed = candidates
        .map(function (a) {
            return '"' + a.name + '" [' + a.type + "]";
        })
        .join(" and ");
    host.error(
        'The account name "' +
            name +
            '" is ambiguous — it matches ' +
            listed +
            ". Use the exact name as it appears in the chart of accounts.",
    );
}

// Resolve a name to an id, or fail loudly. An exact match wins outright; else a single caseless
// match; two of either is ambiguous. Cache first, then one refresh-and-retry, then a 404 naming
// every account that does exist. Never let Firefly invent an account, never guess between two.
async function resolveAccountId(host, name) {
    function pick(accounts) {
        const exact = accounts.filter(function (a) {
            return a.name === name;
        });
        if (exact.length === 1) return exact[0];
        if (exact.length > 1) accountAmbiguous(host, name, exact);
        const caseless = accounts.filter(function (a) {
            return a.name.toLowerCase() === String(name).trim().toLowerCase();
        });
        if (caseless.length === 1) return caseless[0];
        if (caseless.length > 1) accountAmbiguous(host, name, caseless);
        return undefined;
    }
    const found = pick(await loadAccounts(host, false));
    if (found) return found.id;
    const refreshed = await loadAccounts(host, true);
    const retry = pick(refreshed);
    if (retry) return retry.id;
    host.error(
        'No account named "' +
            name +
            '". Existing accounts: ' +
            refreshed
                .map(function (a) {
                    return a.name;
                })
                .join(", "),
    );
}

async function currencyOf(host, name) {
    const accounts = await loadAccounts(host, false);
    const match = accounts.filter(function (a) {
        return a.name.toLowerCase() === String(name).trim().toLowerCase();
    })[0];
    return match ? match.currencyCode : undefined;
}

async function loadCategories(host, refresh) {
    if (!refresh) {
        const cached = host.cache.get("categories");
        if (cached) return cached;
    }
    const body = await fireflyCall(host, "GET", "/api/v1/categories", { query: { limit: 200 } });
    const rows = (body && body.data) || [];
    const categories = rows.map(function (row) {
        return { id: row.id, name: String((row.attributes || {}).name || "") };
    });
    host.cache.set("categories", categories);
    return categories;
}

// Category is resolved to an id, never posted by name, so a typo cannot silently create a category.
async function resolveCategoryId(host, name) {
    function pick(categories) {
        return categories.filter(function (c) {
            return c.name.toLowerCase() === String(name).trim().toLowerCase();
        })[0];
    }
    const found = pick(await loadCategories(host, false));
    if (found) return found.id;
    const refreshed = await loadCategories(host, true);
    const retry = pick(refreshed);
    if (retry) return retry.id;
    host.error(
        'No category named "' +
            name +
            '". Existing categories: ' +
            (refreshed.length
                ? refreshed
                      .map(function (c) {
                          return c.name;
                      })
                      .join(", ")
                : "(none yet)") +
            ". Leave the category out, or ask the User to create it.",
    );
}

// Firefly names a field `source_id`; the model gave a `sourceAccount`. This maps a rejection back
// into the model's own vocabulary so a 422 reads as advice, not as Firefly's internals.
const FIREFLY_FIELD_NAMES = {
    source_id: "sourceAccount",
    source_name: "sourceAccount",
    destination_id: "destinationAccount",
    destination_name: "destinationAccount",
    budget_name: "budgetName",
    category_id: "categoryName",
    category_name: "categoryName",
    currency_code: "currencyCode",
    amount: "amount",
    date: "date",
    description: "description",
    type: "type",
    notes: "notes",
};

function describeRejection(details, splits) {
    const errors = details && details.errors;
    if (!errors || Object.keys(errors).length === 0) return undefined;
    const lines = [];
    const seen = {};
    for (const key of Object.keys(errors)) {
        const messages = errors[key];
        const match = /^transactions\.(\d+)\.(.+)$/.exec(key);
        const index = match ? Number(match[1]) : 0;
        const field = match ? match[2] : key;
        const property = FIREFLY_FIELD_NAMES[field];
        const supplied = property && splits[index] ? splits[index][property] : undefined;
        const label = property || field;
        const where = splits.length > 1 ? " (posting " + (index + 1) + ")" : "";
        const said = messages
            .join(" ")
            .replace(/ID "\d+"/g, supplied !== undefined ? '"' + String(supplied) + '"' : "that account")
            .replace(/ or name ""\.?/g, "");
        const line = label + where + (supplied === undefined ? "" : ' "' + String(supplied) + '"') + ": " + said.trim();
        if (!seen[line]) {
            seen[line] = true;
            lines.push(line);
        }
    }
    return (
        "Firefly refused this posting.\n" +
        lines
            .map(function (l) {
                return "- " + l;
            })
            .join("\n")
    );
}

// One Firefly transaction group -> one row per split, in the model's own field names.
function projectTransactionGroup(group) {
    const attributes = group.attributes || {};
    const splits = attributes.transactions || [];
    return splits.map(function (split) {
        return {
            transactionId: group.id,
            date: String(split.date || "").slice(0, 10),
            description: split.description,
            amount: split.amount,
            currency: split.currency_code,
            from: split.source_name,
            to: split.destination_name,
            category: split.category_name || undefined,
            budget: split.budget_name || undefined,
            bookedUnderKey: split.external_id || undefined,
            tags: split.tags || undefined,
        };
    });
}

// bookkeeping.getBudgetReport — each budget's target and what has been spent, for a period.
// The period is mandatory to Firefly: without it every budget reports spent: null, which reads as
// "nothing spent". Defaults to the current calendar month, first to last day (Firefly rejects
// start === end).
function currentMonth() {
    const now = new Date();
    const y = now.getUTCFullYear();
    const m = now.getUTCMonth();
    return {
        start: new Date(Date.UTC(y, m, 1)).toISOString().slice(0, 10),
        end: new Date(Date.UTC(y, m + 1, 0)).toISOString().slice(0, 10),
    };
}
async function execute(args, host) {
    const month = currentMonth();
    const start = args.start ? String(args.start) : month.start;
    const end = args.end ? String(args.end) : month.end;
    const query = { start: start, end: end };

    const budgetsBody = await fireflyCall(host, "GET", "/api/v1/budgets", { query: query });
    const limitsBody = await fireflyCall(host, "GET", "/api/v1/budget-limits", { query: query });

    const limitByBudget = {};
    for (const row of (limitsBody && limitsBody.data) || []) {
        const a = row.attributes || {};
        const budgetId = a.budget_id;
        const amount = Number(a.amount);
        if (!budgetId || !Number.isFinite(amount)) continue;
        const current = limitByBudget[budgetId];
        if (!current || amount > current.amount) limitByBudget[budgetId] = { amount: amount, currency: a.currency_code };
    }

    return ((budgetsBody && budgetsBody.data) || []).map(function (row) {
        const a = row.attributes || {};
        const spentArray = Array.isArray(a.spent) ? a.spent : [];
        let spent = 0;
        for (const entry of spentArray) spent += Math.abs(Number(entry.sum));
        spent = Number(spent.toFixed(2));
        const limit = limitByBudget[row.id];
        const out = { id: row.id, name: String(a.name || ""), spent: spent };
        // A budget with no target for the period reports no limit, which is not a target of zero.
        if (limit) {
            out.limit = limit.amount;
            out.currency = limit.currency;
        }
        return out;
    });
}
$src4$
            WHEN 'bookkeeping.createAccount' THEN $src5$// Bookkeeping egress — shared prelude (ADR-0025).
//
// This block is prepended to every bookkeeping Operation's Source before it is stored, so each
// Operation reads as its own `execute` plus these helpers. It is the part of FireflyConnector that
// was worth keeping: the HTTP call wrapper, account name -> id resolution, the chart-of-accounts
// cache (now `host.cache`, TTL'd and invalidated by createAccount), category resolution, the 422
// field-name table, and the transaction projection. Everything it reaches is on `host`; there are
// no imports, because the Operation Host hands the Source its one capability rather than loading one.

// Firefly's own internal accounts are not part of any chart of accounts a household books to. This
// is a deny-list on purpose: an allow-list once missed that Firefly answers `liabilities` where it
// accepts `liability`, and hid the payables account (BUG-02).
const INTERNAL_ACCOUNT_TYPES = ["initial-balance", "reconciliation", "import"];
function isBookable(type) {
    return INTERNAL_ACCOUNT_TYPES.indexOf(String(type).toLowerCase()) === -1;
}

function todayIso() {
    return new Date().toISOString().slice(0, 10);
}

// One call to Firefly, through the injected client. The credential is attached by the Host and never
// seen here. A non-2xx throws with Firefly's own message where it gave one — the reader sees exactly
// the HTTP this makes. Callers that need the raw status (postTransaction) use host.http.request.
async function fireflyCall(host, method, path, options) {
    const opts = options || {};
    const response = await host.http.request({ method: method, path: path, query: opts.query, body: opts.body });
    if (!response.ok) {
        const said = response.body && response.body.message ? response.body.message : "Firefly HTTP " + response.status;
        host.error(said);
    }
    return response.body;
}

// The chart of accounts, cached per egress. `refresh` bypasses the cache the way the old connector's
// `listAccounts(true)` did; createAccount evicts the key so a freshly made account is resolvable at once.
async function loadAccounts(host, refresh) {
    if (!refresh) {
        const cached = host.cache.get("accounts");
        if (cached) return cached;
    }
    const body = await fireflyCall(host, "GET", "/api/v1/accounts", { query: { limit: 200 } });
    const rows = (body && body.data) || [];
    const accounts = rows
        .map(function (row) {
            const a = row.attributes || {};
            return {
                id: row.id,
                name: String(a.name || ""),
                type: String(a.type || ""),
                currentBalance: a.current_balance,
                currencyCode: a.currency_code,
            };
        })
        .filter(function (a) {
            return isBookable(a.type);
        });
    host.cache.set("accounts", accounts);
    return accounts;
}

function accountAmbiguous(host, name, candidates) {
    const listed = candidates
        .map(function (a) {
            return '"' + a.name + '" [' + a.type + "]";
        })
        .join(" and ");
    host.error(
        'The account name "' +
            name +
            '" is ambiguous — it matches ' +
            listed +
            ". Use the exact name as it appears in the chart of accounts.",
    );
}

// Resolve a name to an id, or fail loudly. An exact match wins outright; else a single caseless
// match; two of either is ambiguous. Cache first, then one refresh-and-retry, then a 404 naming
// every account that does exist. Never let Firefly invent an account, never guess between two.
async function resolveAccountId(host, name) {
    function pick(accounts) {
        const exact = accounts.filter(function (a) {
            return a.name === name;
        });
        if (exact.length === 1) return exact[0];
        if (exact.length > 1) accountAmbiguous(host, name, exact);
        const caseless = accounts.filter(function (a) {
            return a.name.toLowerCase() === String(name).trim().toLowerCase();
        });
        if (caseless.length === 1) return caseless[0];
        if (caseless.length > 1) accountAmbiguous(host, name, caseless);
        return undefined;
    }
    const found = pick(await loadAccounts(host, false));
    if (found) return found.id;
    const refreshed = await loadAccounts(host, true);
    const retry = pick(refreshed);
    if (retry) return retry.id;
    host.error(
        'No account named "' +
            name +
            '". Existing accounts: ' +
            refreshed
                .map(function (a) {
                    return a.name;
                })
                .join(", "),
    );
}

async function currencyOf(host, name) {
    const accounts = await loadAccounts(host, false);
    const match = accounts.filter(function (a) {
        return a.name.toLowerCase() === String(name).trim().toLowerCase();
    })[0];
    return match ? match.currencyCode : undefined;
}

async function loadCategories(host, refresh) {
    if (!refresh) {
        const cached = host.cache.get("categories");
        if (cached) return cached;
    }
    const body = await fireflyCall(host, "GET", "/api/v1/categories", { query: { limit: 200 } });
    const rows = (body && body.data) || [];
    const categories = rows.map(function (row) {
        return { id: row.id, name: String((row.attributes || {}).name || "") };
    });
    host.cache.set("categories", categories);
    return categories;
}

// Category is resolved to an id, never posted by name, so a typo cannot silently create a category.
async function resolveCategoryId(host, name) {
    function pick(categories) {
        return categories.filter(function (c) {
            return c.name.toLowerCase() === String(name).trim().toLowerCase();
        })[0];
    }
    const found = pick(await loadCategories(host, false));
    if (found) return found.id;
    const refreshed = await loadCategories(host, true);
    const retry = pick(refreshed);
    if (retry) return retry.id;
    host.error(
        'No category named "' +
            name +
            '". Existing categories: ' +
            (refreshed.length
                ? refreshed
                      .map(function (c) {
                          return c.name;
                      })
                      .join(", ")
                : "(none yet)") +
            ". Leave the category out, or ask the User to create it.",
    );
}

// Firefly names a field `source_id`; the model gave a `sourceAccount`. This maps a rejection back
// into the model's own vocabulary so a 422 reads as advice, not as Firefly's internals.
const FIREFLY_FIELD_NAMES = {
    source_id: "sourceAccount",
    source_name: "sourceAccount",
    destination_id: "destinationAccount",
    destination_name: "destinationAccount",
    budget_name: "budgetName",
    category_id: "categoryName",
    category_name: "categoryName",
    currency_code: "currencyCode",
    amount: "amount",
    date: "date",
    description: "description",
    type: "type",
    notes: "notes",
};

function describeRejection(details, splits) {
    const errors = details && details.errors;
    if (!errors || Object.keys(errors).length === 0) return undefined;
    const lines = [];
    const seen = {};
    for (const key of Object.keys(errors)) {
        const messages = errors[key];
        const match = /^transactions\.(\d+)\.(.+)$/.exec(key);
        const index = match ? Number(match[1]) : 0;
        const field = match ? match[2] : key;
        const property = FIREFLY_FIELD_NAMES[field];
        const supplied = property && splits[index] ? splits[index][property] : undefined;
        const label = property || field;
        const where = splits.length > 1 ? " (posting " + (index + 1) + ")" : "";
        const said = messages
            .join(" ")
            .replace(/ID "\d+"/g, supplied !== undefined ? '"' + String(supplied) + '"' : "that account")
            .replace(/ or name ""\.?/g, "");
        const line = label + where + (supplied === undefined ? "" : ' "' + String(supplied) + '"') + ": " + said.trim();
        if (!seen[line]) {
            seen[line] = true;
            lines.push(line);
        }
    }
    return (
        "Firefly refused this posting.\n" +
        lines
            .map(function (l) {
                return "- " + l;
            })
            .join("\n")
    );
}

// One Firefly transaction group -> one row per split, in the model's own field names.
function projectTransactionGroup(group) {
    const attributes = group.attributes || {};
    const splits = attributes.transactions || [];
    return splits.map(function (split) {
        return {
            transactionId: group.id,
            date: String(split.date || "").slice(0, 10),
            description: split.description,
            amount: split.amount,
            currency: split.currency_code,
            from: split.source_name,
            to: split.destination_name,
            category: split.category_name || undefined,
            budget: split.budget_name || undefined,
            bookedUnderKey: split.external_id || undefined,
            tags: split.tags || undefined,
        };
    });
}

// bookkeeping.createAccount — add an account to the chart of accounts. Search-then-create, so a
// repeat is a no-op; the reconcile answers "did it land?" after an interrupted Turn.
async function execute(args, host) {
    const name = String(args.name || "");
    const accounts = await loadAccounts(host, true);
    const existing = accounts.filter(function (a) {
        return a.name.toLowerCase() === name.trim().toLowerCase();
    })[0];
    if (existing) return Object.assign({}, existing, { alreadyExisted: true });

    const type = String(args.type || "expense");
    const body = { name: name, type: type, currency_code: args.currencyCode ? String(args.currencyCode) : "EUR" };
    if (type === "asset") {
        body.account_role = "defaultAsset";
    }
    if (type === "liability" || type === "liabilities") {
        body.type = "liability";
        body.liability_type = "debt";
        body.liability_direction = "credit";
        body.interest = "0";
        body.interest_period = "monthly";
        body.opening_balance = "0";
        body.opening_balance_date = todayIso();
    }

    const created = await fireflyCall(host, "POST", "/api/v1/accounts", { body: body });
    // Evict the chart of accounts so the next listAccounts / resolveAccountId sees the new account
    // at once, rather than waiting out host.cache's TTL. This is what the old accountCache = undefined did.
    host.cache.delete("accounts");
    const a = (created && created.data && created.data.attributes) || {};
    return { id: created.data.id, name: String(a.name || name), type: String(a.type || type) };
}

async function reconcile(args, host) {
    const name = String(args.name || "");
    const accounts = await loadAccounts(host, true);
    const existing = accounts.filter(function (a) {
        return a.name.toLowerCase() === name.trim().toLowerCase();
    })[0];
    if (existing) return Object.assign({}, existing, { alreadyExisted: true });
    host.error('This call was interrupted; no account named "' + name + '" exists.');
}
$src5$
            WHEN 'bookkeeping.postTransaction' THEN $src6$// Bookkeeping egress — shared prelude (ADR-0025).
//
// This block is prepended to every bookkeeping Operation's Source before it is stored, so each
// Operation reads as its own `execute` plus these helpers. It is the part of FireflyConnector that
// was worth keeping: the HTTP call wrapper, account name -> id resolution, the chart-of-accounts
// cache (now `host.cache`, TTL'd and invalidated by createAccount), category resolution, the 422
// field-name table, and the transaction projection. Everything it reaches is on `host`; there are
// no imports, because the Operation Host hands the Source its one capability rather than loading one.

// Firefly's own internal accounts are not part of any chart of accounts a household books to. This
// is a deny-list on purpose: an allow-list once missed that Firefly answers `liabilities` where it
// accepts `liability`, and hid the payables account (BUG-02).
const INTERNAL_ACCOUNT_TYPES = ["initial-balance", "reconciliation", "import"];
function isBookable(type) {
    return INTERNAL_ACCOUNT_TYPES.indexOf(String(type).toLowerCase()) === -1;
}

function todayIso() {
    return new Date().toISOString().slice(0, 10);
}

// One call to Firefly, through the injected client. The credential is attached by the Host and never
// seen here. A non-2xx throws with Firefly's own message where it gave one — the reader sees exactly
// the HTTP this makes. Callers that need the raw status (postTransaction) use host.http.request.
async function fireflyCall(host, method, path, options) {
    const opts = options || {};
    const response = await host.http.request({ method: method, path: path, query: opts.query, body: opts.body });
    if (!response.ok) {
        const said = response.body && response.body.message ? response.body.message : "Firefly HTTP " + response.status;
        host.error(said);
    }
    return response.body;
}

// The chart of accounts, cached per egress. `refresh` bypasses the cache the way the old connector's
// `listAccounts(true)` did; createAccount evicts the key so a freshly made account is resolvable at once.
async function loadAccounts(host, refresh) {
    if (!refresh) {
        const cached = host.cache.get("accounts");
        if (cached) return cached;
    }
    const body = await fireflyCall(host, "GET", "/api/v1/accounts", { query: { limit: 200 } });
    const rows = (body && body.data) || [];
    const accounts = rows
        .map(function (row) {
            const a = row.attributes || {};
            return {
                id: row.id,
                name: String(a.name || ""),
                type: String(a.type || ""),
                currentBalance: a.current_balance,
                currencyCode: a.currency_code,
            };
        })
        .filter(function (a) {
            return isBookable(a.type);
        });
    host.cache.set("accounts", accounts);
    return accounts;
}

function accountAmbiguous(host, name, candidates) {
    const listed = candidates
        .map(function (a) {
            return '"' + a.name + '" [' + a.type + "]";
        })
        .join(" and ");
    host.error(
        'The account name "' +
            name +
            '" is ambiguous — it matches ' +
            listed +
            ". Use the exact name as it appears in the chart of accounts.",
    );
}

// Resolve a name to an id, or fail loudly. An exact match wins outright; else a single caseless
// match; two of either is ambiguous. Cache first, then one refresh-and-retry, then a 404 naming
// every account that does exist. Never let Firefly invent an account, never guess between two.
async function resolveAccountId(host, name) {
    function pick(accounts) {
        const exact = accounts.filter(function (a) {
            return a.name === name;
        });
        if (exact.length === 1) return exact[0];
        if (exact.length > 1) accountAmbiguous(host, name, exact);
        const caseless = accounts.filter(function (a) {
            return a.name.toLowerCase() === String(name).trim().toLowerCase();
        });
        if (caseless.length === 1) return caseless[0];
        if (caseless.length > 1) accountAmbiguous(host, name, caseless);
        return undefined;
    }
    const found = pick(await loadAccounts(host, false));
    if (found) return found.id;
    const refreshed = await loadAccounts(host, true);
    const retry = pick(refreshed);
    if (retry) return retry.id;
    host.error(
        'No account named "' +
            name +
            '". Existing accounts: ' +
            refreshed
                .map(function (a) {
                    return a.name;
                })
                .join(", "),
    );
}

async function currencyOf(host, name) {
    const accounts = await loadAccounts(host, false);
    const match = accounts.filter(function (a) {
        return a.name.toLowerCase() === String(name).trim().toLowerCase();
    })[0];
    return match ? match.currencyCode : undefined;
}

async function loadCategories(host, refresh) {
    if (!refresh) {
        const cached = host.cache.get("categories");
        if (cached) return cached;
    }
    const body = await fireflyCall(host, "GET", "/api/v1/categories", { query: { limit: 200 } });
    const rows = (body && body.data) || [];
    const categories = rows.map(function (row) {
        return { id: row.id, name: String((row.attributes || {}).name || "") };
    });
    host.cache.set("categories", categories);
    return categories;
}

// Category is resolved to an id, never posted by name, so a typo cannot silently create a category.
async function resolveCategoryId(host, name) {
    function pick(categories) {
        return categories.filter(function (c) {
            return c.name.toLowerCase() === String(name).trim().toLowerCase();
        })[0];
    }
    const found = pick(await loadCategories(host, false));
    if (found) return found.id;
    const refreshed = await loadCategories(host, true);
    const retry = pick(refreshed);
    if (retry) return retry.id;
    host.error(
        'No category named "' +
            name +
            '". Existing categories: ' +
            (refreshed.length
                ? refreshed
                      .map(function (c) {
                          return c.name;
                      })
                      .join(", ")
                : "(none yet)") +
            ". Leave the category out, or ask the User to create it.",
    );
}

// Firefly names a field `source_id`; the model gave a `sourceAccount`. This maps a rejection back
// into the model's own vocabulary so a 422 reads as advice, not as Firefly's internals.
const FIREFLY_FIELD_NAMES = {
    source_id: "sourceAccount",
    source_name: "sourceAccount",
    destination_id: "destinationAccount",
    destination_name: "destinationAccount",
    budget_name: "budgetName",
    category_id: "categoryName",
    category_name: "categoryName",
    currency_code: "currencyCode",
    amount: "amount",
    date: "date",
    description: "description",
    type: "type",
    notes: "notes",
};

function describeRejection(details, splits) {
    const errors = details && details.errors;
    if (!errors || Object.keys(errors).length === 0) return undefined;
    const lines = [];
    const seen = {};
    for (const key of Object.keys(errors)) {
        const messages = errors[key];
        const match = /^transactions\.(\d+)\.(.+)$/.exec(key);
        const index = match ? Number(match[1]) : 0;
        const field = match ? match[2] : key;
        const property = FIREFLY_FIELD_NAMES[field];
        const supplied = property && splits[index] ? splits[index][property] : undefined;
        const label = property || field;
        const where = splits.length > 1 ? " (posting " + (index + 1) + ")" : "";
        const said = messages
            .join(" ")
            .replace(/ID "\d+"/g, supplied !== undefined ? '"' + String(supplied) + '"' : "that account")
            .replace(/ or name ""\.?/g, "");
        const line = label + where + (supplied === undefined ? "" : ' "' + String(supplied) + '"') + ": " + said.trim();
        if (!seen[line]) {
            seen[line] = true;
            lines.push(line);
        }
    }
    return (
        "Firefly refused this posting.\n" +
        lines
            .map(function (l) {
                return "- " + l;
            })
            .join("\n")
    );
}

// One Firefly transaction group -> one row per split, in the model's own field names.
function projectTransactionGroup(group) {
    const attributes = group.attributes || {};
    const splits = attributes.transactions || [];
    return splits.map(function (split) {
        return {
            transactionId: group.id,
            date: String(split.date || "").slice(0, 10),
            description: split.description,
            amount: split.amount,
            currency: split.currency_code,
            from: split.source_name,
            to: split.destination_name,
            category: split.category_name || undefined,
            budget: split.budget_name || undefined,
            bookedUnderKey: split.external_id || undefined,
            tags: split.tags || undefined,
        };
    });
}

// bookkeeping.postTransaction — book a balanced transaction. Safe to retry, three ways:
//   1. external_id is the Turn's idempotency key, so a repeat of the same Turn is recognised;
//   2. the thing: tag catches the same posting booked under a *different* key (two Turns, or two
//      Conversations, about one invoice each mint their own key — external_id cannot see those,
//      because it participates in Firefly's duplicate hash, so the differing key defeats that guard);
//   3. Firefly's own error_if_duplicate_hash catches an identical posting, and a corrected journal
//      (one the User deleted) is re-bookable because we retry without the flag once the victim is gone.
// The User must approve the exact posting first — the Runtime enforces that before execute is reached.

// Has a transaction already been booked under this key? The value must be quoted inside Firefly's
// search grammar (external_id_is:"...") or the colon in the key splits it and it matches nothing.
async function findByExternalId(host, externalId) {
    const body = await fireflyCall(host, "GET", "/api/v1/search/transactions", {
        query: { query: 'external_id_is:"' + externalId + '"', limit: 5 },
    });
    const first = body && body.data ? body.data[0] : undefined;
    return first ? { id: first.id } : undefined;
}

// Two postings are the same when their money, date, type and both account ids agree.
function sameSplit(wanted, booked) {
    const amount = (value) => Number(Number(value === undefined || value === null ? NaN : value).toFixed(2));
    return (
        String(booked.date || "").slice(0, 10) === String(wanted.date || "").slice(0, 10) &&
        amount(booked.amount) === amount(wanted.amount) &&
        Number.isFinite(amount(wanted.amount)) &&
        String(booked.type || "") === String(wanted.type || "") &&
        String(booked.source_id || "") === String(wanted.source_id || "") &&
        String(booked.destination_id || "") === String(wanted.destination_id || "")
    );
}

// Is this exact posting already booked against this Thing, under any key? Compared on the content,
// not the tag alone: one invoice may have up to four legitimate journals (book the payable, pay it,
// claim from the insurer, the insurer pays), all carrying the same ThingID, so matching on the tag
// alone would make the payment leg a silent no-op — a worse bug than the one this fixes.
async function findSamePostingForThing(host, thingId, wanted) {
    const body = await fireflyCall(host, "GET", "/api/v1/search/transactions", {
        query: { query: 'tag_is:"thing:' + thingId + '"', limit: 25 },
    });
    for (const group of (body && body.data) || []) {
        const booked = (group.attributes && group.attributes.transactions) || [];
        if (booked.length !== wanted.length) continue;
        const allMatched = wanted.every(function (split) {
            return booked.some(function (candidate) {
                return sameSplit(split, candidate);
            });
        });
        if (allMatched) return group.id;
    }
    return undefined;
}

// The transaction Firefly says this one duplicates, if a 422 said so. The message
// "Duplicate of transaction #14." arrives under a per-split key, so it is matched across all of them.
function duplicateHashVictim(status, body) {
    if (status !== 422) return undefined;
    const errors = (body && body.errors) || {};
    for (const key of Object.keys(errors)) {
        for (const message of errors[key]) {
            const match = /Duplicate of transaction #(\d+)/i.exec(message);
            if (match) return match[1];
        }
    }
    const match = /Duplicate of transaction #(\d+)/i.exec(String((body && body.message) || ""));
    return match ? match[1] : undefined;
}

// Does that journal still exist? Firefly answers a missing one with 401, not 404 — measured. A
// non-2xx that is neither is read as "still there" (conservative: do not re-book over it).
async function transactionExists(host, id) {
    const response = await host.http.request({ method: "GET", path: "/api/v1/transactions/" + id });
    return response.ok || (response.status !== 401 && response.status !== 404);
}

async function execute(args, host) {
    const splits = Array.isArray(args.splits) ? args.splits : [];
    if (splits.length === 0) host.error("postTransaction needs at least one split.");
    const externalId = host.context.idempotencyKey;

    // If this key already landed, this is a retry — return it rather than book a second time.
    const already = await findByExternalId(host, externalId);
    if (already) return { transactionId: already.id, alreadyExisted: true };

    const transactions = [];
    for (const split of splits) {
        const sourceId = await resolveAccountId(host, String(split.sourceAccount || ""));
        const destinationId = await resolveAccountId(host, String(split.destinationAccount || ""));

        if (split.currencyCode) {
            const accountCurrency = await currencyOf(host, String(split.sourceAccount || ""));
            if (accountCurrency && String(split.currencyCode).toUpperCase() !== String(accountCurrency).toUpperCase()) {
                host.error(
                    '"' +
                        split.sourceAccount +
                        '" keeps its books in ' +
                        accountCurrency +
                        ", and this posting is in " +
                        split.currencyCode +
                        ". Firefly would silently store it as " +
                        accountCurrency +
                        " at the same number, so it is refused. Convert the amount to " +
                        accountCurrency +
                        " first, or ask the User which rate to use.",
                );
            }
        }

        const row = {
            type: split.type,
            date: split.date,
            amount: split.amount,
            description: split.description,
            currency_code: split.currencyCode || "EUR",
            source_id: sourceId,
            destination_id: destinationId,
            external_id: externalId,
        };
        if (split.budgetName) row.budget_name = split.budgetName;
        // Category is resolved to an id, never posted by name, so a typo cannot auto-create one.
        if (split.categoryName) row.category_id = await resolveCategoryId(host, String(split.categoryName));
        if (split.notes) row.notes = split.notes;
        // Link the journal back to the Invoice Thing — for a human in Firefly, and for the dedup below.
        if (args.thingId) row.tags = ["thing:" + args.thingId];
        transactions.push(row);
    }

    // The same posting may already be booked under a different key. external_id cannot see it; the
    // thing: tag can. Content-compared, so a genuine second leg of the same invoice still books.
    if (args.thingId) {
        const alreadyForThing = await findSamePostingForThing(host, args.thingId, transactions);
        if (alreadyForThing) return { transactionId: alreadyForThing, alreadyExisted: true };
    }

    const body = { transactions: transactions };
    if (args.groupTitle) body.group_title = args.groupTitle;

    const response = await host.http.request({
        method: "POST",
        path: "/api/v1/transactions",
        body: Object.assign({}, body, { error_if_duplicate_hash: true }),
    });
    if (response.ok) return { transactionId: response.body.data.id, alreadyExisted: false };

    // Firefly's duplicate-hash index outlives a delete while its search does not, so a journal the
    // User removed as a correction would block its own key for ever. Retry without the flag — but
    // ONLY once the named journal is confirmed gone, or this would re-open the double-booking hole.
    const victim = duplicateHashVictim(response.status, response.body || {});
    if (victim !== undefined && !(await transactionExists(host, victim))) {
        const retry = await host.http.request({
            method: "POST",
            path: "/api/v1/transactions",
            body: Object.assign({}, body, { error_if_duplicate_hash: false }),
        });
        if (retry.ok) return { transactionId: retry.body.data.id, alreadyExisted: false };
        const retryDetails = retry.body || {};
        host.error(describeRejection(retryDetails, splits) || retryDetails.message || "Firefly HTTP " + retry.status);
    }

    const details = response.body || {};
    host.error(describeRejection(details, splits) || details.message || "Firefly HTTP " + response.status);
}

async function reconcile(args, host) {
    const landed = await findByExternalId(host, host.context.idempotencyKey);
    if (landed) return { transactionId: landed.id, alreadyExisted: true };
    host.error(
        "This booking was interrupted before it reached the books, so nothing was posted. Book it again if it is still right.",
    );
}
$src6$
            ELSE (d.content::jsonb #>> '{Operation,Source}')
            END
        )
        )
    )
)::text
WHERE d.model_name = 'Operation_DM'
  AND d.content::jsonb #>> '{Operation,Key}' IN ('bookkeeping.getBalance', 'bookkeeping.listAccounts', 'bookkeeping.listOpenItems', 'bookkeeping.listTransactions', 'bookkeeping.getBudgetReport', 'bookkeeping.createAccount', 'bookkeeping.postTransaction')
  AND (d.content::jsonb #>> '{Operation,Implementation}') IS DISTINCT FROM 'dynamic';

-- DOWN-MIGRATION (commented out). Run it in the same offline window as restoring the old image.
--
-- UPDATE document AS d
-- SET content = (
--     d.content::jsonb
--     || jsonb_build_object(
--         'Operation',
--         ((d.content::jsonb -> 'Operation') - 'Source' - 'Language' - 'Egress')
--         || jsonb_build_object('Implementation', 'built-in')
--     )
-- )::text
-- WHERE d.model_name = 'Operation_DM'
--   AND d.content::jsonb #>> '{Operation,Key}' IN ('bookkeeping.getBalance', 'bookkeeping.listAccounts', 'bookkeeping.listOpenItems', 'bookkeeping.listTransactions', 'bookkeeping.getBudgetReport', 'bookkeeping.createAccount', 'bookkeeping.postTransaction')
--   AND (d.content::jsonb #>> '{Operation,Implementation}') = 'dynamic';
